module.exports = {
  processors: ['stylelint-processor-styled-components'],
  extends: ['stylelint-config-recommended', 'stylelint-config-styled-components'],
  plugins: ['stylelint-order'],
  rules: {
    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: ['/-styled-mixin/', '/-styled-mixin0', '$dummyValue'],
      },
    ],
    'property-no-unknown': [
      true,
      {
        checkPrefixed: true,
        ignoreProperties: ['/-styled-mixin/'],
      },
    ],
    'order/properties-order': [
      'box-sizing',
      'display',
      'content',
      'position',
      'z-index',
      'top',
      'right',
      'bottom',
      'left',
      'transform',
      'flex',
      'order',
      'align-self',
      'flex-direction',
      'justify-content',
      'align-items',
      'flex-wrap',
      'align-content',
      'flex-flow',
      'overflow',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'padding',
      'border',
      'margin',
      'list',
      'background',
      'box-shadow',
      'outline',
      'text',
      'white-space',
      'font',
      'line-height',
      'color',
      'animation',
      'transition',
    ],
  },
};
