export const initialStore = [
  {
    id: 1,
    category: 'Fruits & Vegs',
    name: 'Carrots',
    stock: 1.5,
    unit: 'kg',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 2,
    category: 'Fruits & Vegs',
    name: 'Potatoes',
    stock: 3,
    unit: 'kg',
    maxStock: 5,
    minStock: 1,
  },
  {
    id: 3,
    category: 'Fruits & Vegs',
    name: 'Cabbage',
    stock: 0.5,
    unit: 'kg',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 4,
    category: 'Chemicals',
    name: 'Carpet cleaner',
    stock: 1,
    unit: 'pcs',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 5,
    category: 'Chemicals',
    name: 'Dishwashing detergent',
    stock: 0.7,
    unit: 'liter',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 6,
    category: 'Meats & Fishes',
    name: 'Beef steak',
    stock: 1.5,
    unit: 'kg',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 7,
    category: 'Meats & Fishes',
    name: 'Chicken',
    stock: 1,
    unit: 'kg',
    maxStock: 5,
    minStock: 1,
  },
  {
    id: 8,
    category: 'Grains & Nuts',
    name: 'Flour',
    stock: 0.5,
    unit: 'kg',
    maxStock: 1,
    minStock: 1,
  },
  {
    id: 9,
    category: 'Grains & Nuts',
    name: 'Coffee beans',
    stock: 1,
    unit: 'kg',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 10,
    category: 'Grains & Nuts',
    name: 'Rice',
    stock: 1,
    unit: 'kg',
    maxStock: 2,
    minStock: 1,
  },
  {
    id: 11,
    category: 'Dairy Foods',
    name: 'Milk',
    stock: 4,
    unit: 'pcs',
    maxStock: 10,
    minStock: 1,
  },

  {
    id: 12,
    category: 'Drinks',
    name: 'Wine',
    stock: 2,
    unit: 'pcs',
    maxStock: 5,
    minStock: 1,
  },
  {
    id: 13,
    category: 'Drinks',
    name: 'Cola Bottle 2L',
    stock: 1,
    unit: 'pcs',
    maxStock: 2,
    minStock: 1,
  },
];
